server:
  port: 8080
  servlet:
    context-path: /


spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/auction_web}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:120503}
    username: ${DBMS_USERNAME:root}

# spring:
#   datasource:
#     url: ${DBMS_CONNECTION:jdbc:mysql://root:AcvMDoekXnSFbjMntWyhGNXDbBusxyjb@autorack.proxy.rlwy.net:55890/railway}
#     driverClassName: "com.mysql.cj.jdbc.Driver"
#     password: ${DBMS_PASSWORD:root}
#     username: ${DBMS_USERNAME:AcvMDoekXnSFbjMntWyhGNXDbBusxyjb}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-server:9000


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: "redis-19216.c266.us-east-1-3.ec2.redns.redis-cloud.com"
      port: 19216

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 7200 # in second
  refreshable-duration: 1728000 # in seconds

email:
  username: webonlineauction@gmail.com
  password: hrqqaszjtpqqjchc

redis:
  host: "redis-19216.c266.us-east-1-3.ec2.redns.redis-cloud.com"
  port: "19216"
  password: "dVDInguT3Iw5sP9cpjUPhO4J5QMBfgbm"

cloudinary:
    cloud-name: "da7ocjpcu"
    api-key: "243495346747181"
    api-secret: "bD1q8wkCmh1HV0blM7zyFdrrSVk"

quartz:
  auto-startup: true
  overwrite-existing-jobs: true
  job-store-type: jdbc
  jdbc:
    initialize-schema: always
    properties:
        org:
            quartz:
            scheduler:
                instanceName: MyScheduler
                instanceId: AUTO
            jobStore:
                class: org.quartz.impl.jdbcjobstore.JobStoreTX
                driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
                tablePrefix: QRTZ_
                isClustered: true
                clusterCheckinInterval: 20000
                dataSource: myDS
            threadPool:
                class: org.quartz.simpl.SimpleThreadPool
                threadCount: 25
                threadPriority: 5
            dataSource:
                myDS:
                driver: com.mysql.cj.jdbc.Driver
                URL: jdbc:mysql://localhost:3306/auction_web
                user: root
                password: root
                maxConnections: 5
                validationQuery: select 1